# Generated by Django 3.2.9 on 2021-12-05 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='スキル名')),
                ('category', models.IntegerField(blank=True, choices=[(0, None), (1, '言語'), (2, 'フレームワーク'), (3, 'データベース、サーバー等')], default=0, null=True, verbose_name='スキル種別')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='サービス名')),
                ('outline', models.TextField(blank=True, default='', verbose_name='概要')),
                ('description', models.TextField(blank=True, default='', verbose_name='内容')),
                ('service_url', models.URLField(blank=True, null=True, verbose_name='サービスURL')),
                ('code_url', models.URLField(blank=True, null=True, verbose_name='ソースコード')),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.profile', verbose_name='開発者')),
                ('skills', models.ManyToManyField(related_name='skill_detail', to='portfolio.Skill', verbose_name='使用言語等')),
            ],
        ),
    ]
